on: 
  push:
      branches: [main]
      paths: &paths
        - ".storybook/**/*"
        - "stories/**/*"
        - "src/theme/**/*.ts"
  pull_request:
      paths: *paths

name: 'Chromatic'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies & build
        run: |
          yarn install --immutable
          yarn build
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}